### PR TITLE
chore: updates libp2p-crypto-secp256k1

### PR DESCRIPTION
**Pull request by AlbertoElias**
Hey @dignifiedquire It seems like this repo also needs to update the dependency as https://github.com/libp2p/js-libp2p-keychain depends on this one

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Jenkins error says: `No space left on device` Not sure how to fix that, I don't work for Protocol Labs so I don't have access to anything

**Comment by vasco-santos** [comment]
We are switching all our CI for travis. So, I just created [js-libp2p-crypto#138](https://github.com/libp2p/js-libp2p-crypto/pull/138) for switching it. Once it gets merged, please rebase this PR with master and you will have travis running for the PR

**Comment by AlbertoElias** [comment]
@vasco-santos done!

**Comment by AlbertoElias** [comment]
Great! So when can this and keychain be released? And what's the process to that moving down to js-ipfs? Thanks!

**Comment by vasco-santos** [comment]
Once @dignifiedquire is ready to review and release this, I will be able to release `libp2p-keychain`! After that, we can have a look, but I would say that we need to update the versions of the dependencies, and then add in the key api the type to use

**Comment by AlbertoElias** [comment]
Great! If there's anything I can do to accelerate the process, please let me know, I'm really keen on these features

**Comment by dignifiedquire** [comment]
published

**Comment by AlbertoElias** [comment]
@dignifiedquire Thank you!

**Pull request merged**
